# Generated by Django 5.1.5 on 2025-02-04 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="courseType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="images/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BR", "Beginner"),
                            ("IE", "Intermediate"),
                            ("AD", "Advanced"),
                        ],
                        default="BR",
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
