# Generated by Django 5.1.5 on 2025-02-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tutorial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("BR", "Beginner"),
                    ("IE", "Intermediate"),
                    ("AD", "Advanced"),
                ],
                max_length=2,
            ),
        ),
    ]
